cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

heavyaura/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('user/', include('users.urls', namespace='user')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)
    

cart/views.py
from django.shortcuts import render, redirect, \
    get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Cart{% endblock title %}

{% block content %}
    <section class="cart d-flex">
        <div class="cart-title">
            <h2>Shopping Cart</h2>
        </div>
        <div class="cart-cards">
            {% for item in cart %}
                {% with product=item.product %}
                    <div class="cart-card d-flex">
                        <div class="cart-card-img">
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/noimage.jpg' %}{% endif %}" alt="">
                        </div>
                        <div class="cart-card-info">
                            <div class="cart-card-name">
                                <p>{{ product.name }}</p>
                            </div>
                            <div class="cart-card-q">
                                <p>Quantity: {{ item.quantity }}</p>
                            </div>
                        </div>
                        <form action="{% url "cart:cart_remove" product.id %}" method="post">
                            <input type="submit" value="Remove" class="remove-btn">
                            {% csrf_token %}
                        </form>
                        <div class="cart-card-price">
                            {% if product.discount %}
                                <div class="cart-discount d-flex gap-2">
                                    <p class="line">$ {{ product.price }}</p>
                                    <p>$ {{ product.sell_price }}</p>
                                </div>
                            {% else %}
                                <p class="price mt-3">$ {{ product.price }}</p>
                            {% endif %}
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
        </div>
        <div class="total">
            <h5>Total sum: $ {{ cart.get_total_price }}</h5>
        </div>
        <div class="cart-buttons d-flex gap-3">
            <a href="/shop" class="cart-btn">Continue Shopping</a>
            {% with cart_quantity=cart|length %}
                {% if cart_quantity > 0 %}
                    <a href="{% url "orders:order_create" %}" class="cart-btn">Checkout</a>
                {% endif %}
            {% endwith %}
        </div>
    </section>
{% endblock content %}